<?php
/**
 * List of SVG files used in the theme
 *
 * @package mycompany
 * @subpackage Admin
 * @since 0.1
 *
 
 * @license **LICENSE**
 * @version 1.10.3
 */

return array(
    ''                   => __('No Icon', 'my_theme-admin-td'),
    'allign-justify'     => __('Allign Justify', 'my_theme-admin-td'),
    'allign-right'       => __('Allign Right', 'my_theme-admin-td'),
    'angle-down'         => __('Angle Down', 'my_theme-admin-td'),
    'angle-left'         => __('Angle Left', 'my_theme-admin-td'),
    'angle-right'        => __('Angle Right', 'my_theme-admin-td'),
    'angle-up'           => __('Angle Up', 'my_theme-admin-td'),
    'arrow-down-circle'  => __('Arrow Down Circle', 'my_theme-admin-td'),
    'arrow-down'         => __('Arrow Down', 'my_theme-admin-td'),
    'arrow-left-circle'  => __('Arrow Left Circle', 'my_theme-admin-td'),
    'arrow-left'         => __('Arrow Left', 'my_theme-admin-td'),
    'arrow-right-circle' => __('Arrow Right Circle', 'my_theme-admin-td'),
    'arrow-right'        => __('Arrow Right', 'my_theme-admin-td'),
    'arrow-up-circle'    => __('Arrow Up Circle', 'my_theme-admin-td'),
    'arrow-up'           => __('Arrow Up', 'my_theme-admin-td'),
    'ballpoint'          => __('Ballpoint', 'my_theme-admin-td'),
    'battery-empty'      => __('Battery Empty', 'my_theme-admin-td'),
    'battery-full'       => __('Battery Full', 'my_theme-admin-td'),
    'battery'            => __('Battery', 'my_theme-admin-td'),
    'book'               => __('Book', 'my_theme-admin-td'),
    'briefcase-closed'   => __('Briefcase Closed', 'my_theme-admin-td'),
    'briefcase-empty'    => __('Briefcase Empty', 'my_theme-admin-td'),
    'briefcase-full'     => __('Briefcase Full', 'my_theme-admin-td'),
    'brush'              => __('Brush', 'my_theme-admin-td'),
    'bullhorn'           => __('Bullhorn', 'my_theme-admin-td'),
    'calculator'         => __('Calculator', 'my_theme-admin-td'),
    'calendar'           => __('Calendar', 'my_theme-admin-td'),
    'camera'             => __('Camera', 'my_theme-admin-td'),
    'clipboard'          => __('Clipboard', 'my_theme-admin-td'),
    'clock'              => __('Clock', 'my_theme-admin-td'),
    'cloud-download'     => __('Cloud Download', 'my_theme-admin-td'),
    'cloud-upload'       => __('Cloud Upload', 'my_theme-admin-td'),
    'cloud'              => __('Cloud', 'my_theme-admin-td'),
    'cog'                => __('Cog', 'my_theme-admin-td'),
    'cogs'               => __('Cogs', 'my_theme-admin-td'),
    'compass'            => __('Compass', 'my_theme-admin-td'),
    'compass-alt'        => __('Compass Alt', 'my_theme-admin-td'),
    'controls'           => __('Controls', 'my_theme-admin-td'),
    'danger'             => __('Danger', 'my_theme-admin-td'),
    'dashboard'          => __('Dashboard', 'my_theme-admin-td'),
    'disks'              => __('Disks', 'my_theme-admin-td'),
    'doc-alt'            => __('Doc Alt', 'my_theme-admin-td'),
    'doc'                => __('Doc', 'my_theme-admin-td'),
    'docs'               => __('Docs', 'my_theme-admin-td'),
    'down-circle'        => __('Down Circle', 'my_theme-admin-td'),
    'download'           => __('Download', 'my_theme-admin-td'),
    'drop'               => __('Drop', 'my_theme-admin-td'),
    'envelope-closed'    => __('Envelope Closed', 'my_theme-admin-td'),
    'envelope-full'      => __('Envelope Full', 'my_theme-admin-td'),
    'envelope-open'      => __('Envelope Open', 'my_theme-admin-td'),
    'eye'                => __('Eye', 'my_theme-admin-td'),
    'flag'               => __('Flag', 'my_theme-admin-td'),
    'flag-alt'           => __('Flag ALt', 'my_theme-admin-td'),
    'floppy'             => __('Floppy', 'my_theme-admin-td'),
    'folder-closed'      => __('Folder Closed', 'my_theme-admin-td'),
    'folder-empty'       => __('Folder Empty', 'my_theme-admin-td'),
    'folder-full'        => __('Folder Full', 'my_theme-admin-td'),
    'gift'               => __('Gift', 'my_theme-admin-td'),
    'glass'              => __('Glass', 'my_theme-admin-td'),
    'glasses'            => __('Glasses', 'my_theme-admin-td'),
    'globe-alt'          => __('Globe Alt', 'my_theme-admin-td'),
    'globe'              => __('Globe', 'my_theme-admin-td'),
    'graph'              => __('Graph', 'my_theme-admin-td'),
    'graph-alt'          => __('Graph Alt', 'my_theme-admin-td'),
    'grid'               => __('Grid', 'my_theme-admin-td'),
    'heart'              => __('Heart', 'my_theme-admin-td'),
    'home'               => __('Home', 'my_theme-admin-td'),
    'idea'               => __('Idea', 'my_theme-admin-td'),
    'imac'               => __('iMac', 'my_theme-admin-td'),
    'image'              => __('Image', 'my_theme-admin-td'),
    'key'                => __('Key', 'my_theme-admin-td'),
    'lifebuoy'           => __('Lifebuoy', 'my_theme-admin-td'),
    'link'               => __('Link', 'my_theme-admin-td'),
    'list'               => __('List', 'my_theme-admin-td'),
    'macbook'            => __('Macbook', 'my_theme-admin-td'),
    'map-pin'            => __('Map Pin', 'my_theme-admin-td'),
    'map'                => __('Map', 'my_theme-admin-td'),
    'mic'                => __('Mic', 'my_theme-admin-td'),
    'minus-round'        => __('Minus Round', 'my_theme-admin-td'),
    'mobile'             => __('Mobile', 'my_theme-admin-td'),
    'moon'               => __('Moon', 'my_theme-admin-td'),
    'movie'              => __('Movie', 'my_theme-admin-td'),
    'mug'                => __('Mug', 'my_theme-admin-td'),
    'music'              => __('Music', 'my_theme-admin-td'),
    'network'            => __('Network', 'my_theme-admin-td'),
    'padlock-closed'     => __('Padlock Closed', 'my_theme-admin-td'),
    'padlock-open'       => __('Padlock Open', 'my_theme-admin-td'),
    'paperclip'          => __('Paperclip', 'my_theme-admin-td'),
    'pencil'             => __('Pencil', 'my_theme-admin-td'),
    'phone'              => __('Phone', 'my_theme-admin-td'),
    'pie-chart'          => __('Pie Chart', 'my_theme-admin-td'),
    'pirate'             => __('Pirate', 'my_theme-admin-td'),
    'plus'               => __('Plus', 'my_theme-admin-td'),
    'plus-round'         => __('Plus Round', 'my_theme-admin-td'),
    'power'              => __('Power', 'my_theme-admin-td'),
    'print'              => __('Print', 'my_theme-admin-td'),
    'radio-active'       => __('Radio Active', 'my_theme-admin-td'),
    'recycle'            => __('Recycle', 'my_theme-admin-td'),
    'ribbon-alt'         => __('Ribbon Alt', 'my_theme-admin-td'),
    'ribbon'             => __('Ribbon', 'my_theme-admin-td'),
    'scissors'           => __('Scissors', 'my_theme-admin-td'),
    'search'             => __('Search', 'my_theme-admin-td'),
    'server'             => __('Server', 'my_theme-admin-td'),
    'shield'             => __('Shield', 'my_theme-admin-td'),
    'shopping-basket'    => __('Shopping Basket', 'my_theme-admin-td'),
    'signal-strong'      => __('Signal Strong', 'my_theme-admin-td'),
    'signal-weak'        => __('Signal Weak', 'my_theme-admin-td'),
    'sound-full'         => __('Sound Full', 'my_theme-admin-td'),
    'sound-low'          => __('Sound Low', 'my_theme-admin-td'),
    'sound-mute'         => __('Sound Mute', 'my_theme-admin-td'),
    'speech-bubble'      => __('Speech Bubble', 'my_theme-admin-td'),
    'star'               => __('Star', 'my_theme-admin-td'),
    'sun'                => __('Sun', 'my_theme-admin-td'),
    'tablet'             => __('Tablet', 'my_theme-admin-td'),
    'target'             => __('Target', 'my_theme-admin-td'),
    'test'               => __('Test', 'my_theme-admin-td'),
    'trashcan'           => __('Trashcan', 'my_theme-admin-td'),
    'tshirt-alt'         => __('Tshirt Alt', 'my_theme-admin-td'),
    'tshirt'             => __('Tshirt', 'my_theme-admin-td'),
    'up-circle'          => __('Up Circle', 'my_theme-admin-td'),
    'upload'             => __('Upload', 'my_theme-admin-td'),
    'user'               => __('User', 'my_theme-admin-td'),
    'users'              => __('Users', 'my_theme-admin-td'),
    'weather-cloudy-sun' => __('Weather Cloudy Sun', 'my_theme-admin-td'),
    'weather-cloudy'     => __('Weather Cloudy', 'my_theme-admin-td'),
    'weather-rainy'      => __('Weather Rainy', 'my_theme-admin-td'),
    'weather-snowy'      => __('Weather Snowy', 'my_theme-admin-td'),
    'weather-stormy'     => __('Weather Stormy', 'my_theme-admin-td'),
    'weather-sun-cloudy' => __('Weather Sun Cloudy', 'my_theme-admin-td'),
    'wrench'             => __('Wrench', 'my_theme-admin-td'),
);